name: 'Deploy to Render'

on:
  push:
    branches:
      - main

env:
  SENTRY_ORG: 'colognifornia'
  SENTRY_PROJECT: 'consent_colognifornia_com'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Build'
        run: |
          npm ci
          npm run build

      - name: 'Create Sentry release and generate sourcemaps'
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ env.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ env.SENTRY_PROJECT }}
        with:
          environment: production
          inject: true
          sourcemaps: './dist'
          version: 'consent.colognifornia.com@${{ github.sha }}'

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
